#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./colors || exit 1

ABOUT=(
    "Hey! I'm Jisan and i'm "
    "opening those black boxes"
    "just to see what's inside."
)


for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done


# ABOUT=(
# 	"CSE student @ IUT."
# 	"Interested in systems,"
# 	"algorithms, embedded tech,"
# 	"and understanding computers"
# 	"a little deeper every day."
# )


# ABOUT=(
# 	"Hello, what's up my name's Jisan"
# 	"and i am interested in systems,"
#     "algorithms, embedded tech, and exploring"
#     "machine learning and intelligent systems."
#     "I like understanding how things work"
#     "a little deeper every day."
# )