#!/usr/bin/env bash

. ./colors || exit

{
./make-header -p 5 | ./tools/box -hp 1 -T plain

echo
{
    echo "${COLOR3}Languages:${RST}"
    echo "${COLOR5}- Bash / Shell Scripting${RST}"
    echo "${COLOR5}- C / C++${RST}"
    echo "${COLOR5}- Python${RST}"
    echo "${COLOR5}- JavaScript / HTML / CSS${RST}"
    echo "${COLOR5}- Java${RST}"
    echo
    echo "${COLOR3}Tools & Platforms:${RST}"
    echo "${COLOR5}- Linux / Unix (macOS)${RST}"
    echo "${COLOR5}- Git & GitHub${RST}"
    echo "${COLOR5}- Docker${RST}"
} | ./tools/box -hp 2 -vp 1 -bc "$COLOR4" -tc "$COLOR5" -s '|' -t 'Skills'

echo
./make-legend

} | ./tools/rtrim-ansi-aware
