#!/usr/bin/env bash
#
# Loop each episode and generate a tab-separated list of all episodes seen to
# stdout
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

dir=${1:-../episodes}

for pt in "$dir"/pt*/meta.txt; do
	# Read all lines into an array using while-read
	lines=()
	while IFS= read -r _line || [[ -n $_line ]]; do
		lines+=("$_line")
	done < "$pt"

	# read the meta at the top
	title=${lines[0]}
	num=${title%%.*}
	title=${title#*. }
	link=/v/$num
	desc=${lines[1]}

	# read the key values pairs at the bottom
	tiktok=
	youtube=
	instagram=
	for _line in "${lines[@]:2}"; do
		read -r key value <<< "$_line"
		[[ -n $key && -n $value ]] || continue
		case "$key" in
			tiktok) tiktok=$value;;
			youtube) youtube=$value;;
			instagram) instagram=$value;;
		esac
	done

	[[ -n $tiktok && -n $youtube && -n $instagram ]] || continue

	printf '%s\t' "$num" "$title" "$desc" "$link" "$tiktok" "$youtube" "$instagram"
	echo
done
