#!/usr/bin/env bash
#
# Generate the page as seen by `curl mhpx.pages.dev`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./colors || exit

{
./make-header -p 5 |
    ./tools/box -hp 1 -T plain

./make-news

./make-body

./make-legend

} | ./tools/rtrim-ansi-aware
