#!/usr/bin/env bash
#
# Create the JSONP file for the commands to execute on index.html using the
# terminal emulator as seen from the web browser.
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 03, 2025
# License: MIT

# we can declare multiple commands here, but for now i just like having 1
cmd_keys=('curl mhp.sh')
cmd_vals=("$(./make-index | ./tools/bansi-to-html -H)")

inputs=()
for ((i = 0; i < ${#cmd_keys[@]}; i++)); do
	cmd=${cmd_keys[i]}
	output=${cmd_vals[i]}
	s=$(jq -cnR --arg cmd "$cmd" '{
	    "cmd": $cmd,
	    "lines": [inputs]
	}' <<< "$output") || exit 1
	inputs+=("$s")
done

json=$(printf '%s\n' "${inputs[@]}" | jq -cn '[inputs]') || exit 1
echo "const COMMANDS = $json;"
